//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 11/09/2016 20:27:01
namespace HTCVive
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/onepointfive_texture.png </summary>
            public const string onepointfive_texture_png = "Content/Assets/onepointfive_texture.png";
            
            /// <summary> Path to Content/Assets/vr_controller_vive_1_5.obj </summary>
            public const string vr_controller_vive_1_5_obj = "Content/Assets/vr_controller_vive_1_5.obj";
            
            /// <summary> Path to Content/Assets/MyMaterial.wmat </summary>
            public const string MyMaterial = "Content/Assets/MyMaterial.wmat";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
